# catalog-info.yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pet-store-api
  description: Pet store API
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  definition: |
    $text: https://petstore.swagger.io/v2/swagger.json